name: CI/CD - 02 - GitHub Action CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Run tests
        run: |
          sleep 30  # Add a delay of 30 seconds
          python -m unittest discover
        working-directory: ci-cd/02-github-action-ci
