name: CI/CD - 02 - GitHub Actions with Docker CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and test with Docker
        run: |
          docker build -t app-test .
          docker run app-test
        working-directory: ci-cd/03-github-action-docker
